apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: todo-app
  template:
    metadata:
      labels:
        run: todo-app
    spec:
      containers:
      - name: todo-app
        image: aharoacr01.westus2.data.azurecr.io/testing_app:latest
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
        securityContext:
          allowPrivilegeEscalation: false
      imagePullSecrets:
        - name: acr-secret01
      