apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app03
spec:
  replicas: 2
  selector:
    matchLabels:
      run: todo-app03
  template:
    metadata:
      labels:
        run: todo-app03
    spec:
      imagePullSecrets:
        - name: acr-secret02
      containers:
      - name: todo-app03
        image: aharoacr01.azurecr.io/testing_app:latest
        ports:
          - containerPort: 80
        imagePullPolicy: Always
      
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
        securityContext:
          allowPrivilegeEscalation: false
      
      