replicaCount: 1
image:
  repository: aharoacr01.azurecr.io/testing_app
  tag: latest
  pullPolicy: IfNotPresent
# Container & Service port

ports:
  - name: http
    containerPort: 3000
    protocol: TCP

service:
  type: LoadBalancer
  ports: 
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: internal-app

# Port to check if the application is ready
readinessProbe:
    httpGet:
      path: /health
      port: 5002
    initialDelaySeconds: 60
    periodSeconds: 50
# Port to check if the app is already live
livenessProbe:
    httpGet:
      path: /health
      port: 5002
    initialDelaySeconds: 60
    periodSeconds: 50